on:
  push:
    branches:
      - main

name: Build and deploy
jobs:
  builds:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile in back end
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          envkey_DATABASE_URL: ${{secrets.DATABASE_URL}}
          file_name: back-end/.env
      - name: Make a new envfile in front end
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          file_name: front-end/.env

      - name: Inactive Docker-Compose
        run: docker-compose down -v

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose up -d
